### ISSUE TITLE
Error when placing armor stand

### ISSUE THREAD

**Issue by slainless** [ochotonida/curious-armor-stands#4]
Throwing error when placing an armor stand. Also, the armor stand is not placed.

- Version 2.1.2 
- Curious 4.0.6.6
- MC 1.16.5

```
[08:30:27] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: HIGHEST
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@7880b0cd onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		2: NORMAL
		3: ASM: class curiousarmorstands.CuriousArmorStands$Events entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
		4: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@686033cc entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
java.lang.NullPointerException
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.flagUpdate(CurioStacksHandler.java:405)
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addTransientModifier(CurioStacksHandler.java:385)
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addPermanentModifier(CurioStacksHandler.java:389)
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addLegacyChange(CurioStacksHandler.java:141)
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.grow(CurioStacksHandler.java:128)
	at curiousarmorstands.CurioInventoryCapability$CurioInventoryWrapper.lambda$growSlotType$1(CurioInventoryCapability.java:116)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at curiousarmorstands.CurioInventoryCapability$CurioInventoryWrapper.growSlotType(CurioInventoryCapability.java:116)
	at top.theillusivec4.curios.server.SlotHelper.lambda$growSlotType$7(SlotHelper.java:121)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165)
	at top.theillusivec4.curios.server.SlotHelper.growSlotType(SlotHelper.java:120)
	at top.theillusivec4.curios.server.SlotHelper.setSlotsForType(SlotHelper.java:107)
	at curiousarmorstands.CuriousArmorStands$Events.entityJoinWorld(CuriousArmorStands.java:69)
	at net.minecraftforge.eventbus.ASMEventHandler_1_Events_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813)
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11)
	at net.minecraft.item.ArmorStandItem.func_195939_a(SourceFile:54)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644)
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186)
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350)
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36)
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:834)

[08:30:27] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.flagUpdate(CurioStacksHandler.java:405) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addTransientModifier(CurioStacksHandler.java:385) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addPermanentModifier(CurioStacksHandler.java:389) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.addLegacyChange(CurioStacksHandler.java:141) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at top.theillusivec4.curios.common.inventory.CurioStacksHandler.grow(CurioStacksHandler.java:128) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at curiousarmorstands.CurioInventoryCapability$CurioInventoryWrapper.lambda$growSlotType$1(CurioInventoryCapability.java:116) ~[curious_armor_stands:1.16.5-2.1.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?] {}
	at curiousarmorstands.CurioInventoryCapability$CurioInventoryWrapper.growSlotType(CurioInventoryCapability.java:116) ~[curious_armor_stands:1.16.5-2.1.2] {re:classloading}
	at top.theillusivec4.curios.server.SlotHelper.lambda$growSlotType$7(SlotHelper.java:121) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[forge:?] {re:classloading}
	at top.theillusivec4.curios.server.SlotHelper.growSlotType(SlotHelper.java:120) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at top.theillusivec4.curios.server.SlotHelper.setSlotsForType(SlotHelper.java:107) ~[curios:property(class java.lang.String, provider(?))] {re:classloading}
	at curiousarmorstands.CuriousArmorStands$Events.entityJoinWorld(CuriousArmorStands.java:69) ~[curious_armor_stands:1.16.5-2.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1_Events_entityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:classloading}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:classloading}
	at net.minecraft.item.ArmorStandItem.func_195939_a(SourceFile:54) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:644) ~[forge:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
```

**Comment by ochotonida** [comment]
Thanks for the report. I've uploaded a patch that fixes the issue
